[package]
name = "mars_base"
version = "0.1.0"
edition = "2024"

[dependencies]

[workspace.dependencies]
bevy = "0.16"
bevy_egui = "0.34"
rand = "0.8"
rand_pcg = { version = "0.3" }
rand_xorshift = { version = "0.3" }
anyhow = "1"

[workspace]
members = ["mars_base_one","my_library"]
