[package]
name = "mars_base_one"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
my_library = { path = "../my_library" }
anyhow = { workspace = true }
serde = { version = "1.0.210", features = ["derive"] }
ureq = { version = "2", features = ["json"] }
